### ISSUE TITLE
no longer getting stream details

### ISSUE THREAD

**Issue by celina** [joaopsys/NowStreaming#1]
This extension is no longer getting the stream details from Twitch.

**Comment by joaopsys** [comment]
Hi celina,
I can't really reproduce this issue. I've tested both in Linux, Windows and MacOS and it always seems to work for me.

Would you be able to give me the console output?

**Comment by joaopsys** [comment]
Would you also be able to export your streamer list (Options -> Export Data) and send it to me so I can try to replicate the issue? If you prefer not to do that, I completely understand.

**Comment by celina** [comment]
Thank you for your quick response! It looks like it could be a problem with the export/import function.

an example export:
`{"youjelly":{"created_at":"null","flag":0,"game":"null","notify":true,"title":"null","url":"null","viewers":-1}}`

My list wasn't updating with the current stream status so I exported my list, removed the extension, readded it and reimported my list. On import none of the streamer links work, stream status doesn't load, the viewers say -1, and no game is identified.

**Comment by joaopsys** [comment]
Hi celina. I've tried importing just that streamer and I can't replicate the issue. If you import just that one streamer, does the issue still happen?

I'm asking this because there might be one streamer that you're following with a...special title in his stream, which may cause this behavior, which is why I was asking for the list of streamers.

**Comment by celina** [comment]
Here is the full list of streamers:

`list removed to protect privacy`

**Comment by joaopsys** [comment]
Hi celina. For some reason there is a space at the end of "kimchi" (the streamer name). Please remove that space and do the import again.

I will release a fix for this soon!

**Comment by celina** [comment]
Thank you!
