### ISSUE TITLE
Crashes Edge (terminates Edge process) on attempting to Auth to Twitch

### ISSUE THREAD

**Issue by NjnaGrimsdottir** [joaopsys/NowStreaming#5]
subject says everything.  I click authenticate.  Edge closes.

**Comment by CyanSlinky** [comment]
Same thing happening here.

**Comment by joaopsys** [comment]
Hi, this is unfortunately a bug on Microsoft's end - https://techcommunity.microsoft.com/t5/discussions/edge-stable-crashing-on-extension-function-chrome-identity/m-p/2904069

They are working on it, so I believe it will be fixed quite soon.

**Comment by NjnaGrimsdottir** [comment]
There's a workaround published here @joaopsys if you are not interested in waiting for MS to resolve the issue themselves.
https://stackoverflow.com/questions/70187797/chrome-extension-crashes-the-microsoft-edge-browser-while-calling-launchwebauthf?noredirect=1#comment124087889_70187797

**Comment by joaopsys** [comment]
I did see that workaround, but it's too dirty since it doesn't use the native identity API, so I don't want to risk it for Chrome/Firefox users, which currently have identity.launchWebAuthFlow working as it should.

**Comment by joaopsys** [comment]
This has now been fixed by Microsoft on Edge version 98.0.1108.43
