### ISSUE TITLE
Chrome Addon Stop Working

### ISSUE THREAD

**Issue by Kuroo2021** [joaopsys/NowStreaming#9]
Hello I can authorized the application with Twitch but after that it doesn't show any issues Firefox version still worked.
- Try to deauthorized but the app. doesn't allow it.
- Reinstall application and authorized not working
-  Ran the application in incognito authorizes application with Twitch again and still nothing.
- With all these I try to input my watch list with the application but not working.
Version 3.4

**Comment by joaopsys** [comment]
Hi, I have just tested this on the latest version of Chrome (127.0.6533.73 (Official Build) (64-bit)) in different operating systems and everything works flawlessly.

Version 3.5 will release soon, perhaps that will fix your issues, but this seems to be a problem with your own environment.
